[package]
name = "boton"
version = "0.1.0"
authors = ["wwared"]
edition = "2018"

[dependencies]
bytes = "1"
tokio = { version = "1", features = ["full"] }
nom = "6"
log = "0.4"
env_logger = "0.8"
anyhow = "1"
tokio-native-tls = "0.3.0"
ron = "*"
serde = "1"
